import { createSlug } from "../utils/createSlug.js";

export const categoryDefinitions = {
  Writing: {
    description: "Copywriting, drafting, rewriting, and long-form content creation tools.",
    icon: "Sparkles",
    color: "from-blue-500 to-cyan-400",
  },
  "Image Generation": {
    description: "Image creation, concept art, branding visuals, and graphic generation tools.",
    icon: "Image",
    color: "from-fuchsia-500 to-pink-400",
  },
  "Video Editing": {
    description: "Video generation, editing, repurposing, subtitles, and motion content tools.",
    icon: "Clapperboard",
    color: "from-orange-500 to-amber-400",
  },
  "Audio / Voice": {
    description: "Voice synthesis, dubbing, music generation, and speech intelligence tools.",
    icon: "Mic2",
    color: "from-indigo-500 to-blue-500",
  },
  Chatbots: {
    description: "Chatbot building, conversational workflows, support automation, and agent tools.",
    icon: "Bot",
    color: "from-cyan-500 to-sky-400",
  },
  Coding: {
    description: "Code generation, developer assistants, UI generation, and engineering tools.",
    icon: "Code2",
    color: "from-emerald-500 to-lime-400",
  },
  Productivity: {
    description: "Knowledge, note-taking, task management, and meeting productivity tools.",
    icon: "Brain",
    color: "from-sky-500 to-blue-400",
  },
  Research: {
    description: "Search, academic discovery, citations, and research workflow tools.",
    icon: "SearchCheck",
    color: "from-violet-500 to-indigo-400",
  },
  SEO: {
    description: "SEO optimization, rankings, keyword research, and content performance tools.",
    icon: "SearchCheck",
    color: "from-purple-500 to-indigo-400",
  },
  Marketing: {
    description: "Campaigns, ads, outreach, copy optimization, and performance marketing tools.",
    icon: "Megaphone",
    color: "from-rose-500 to-red-400",
  },
  "Social Media": {
    description: "Social publishing, content planning, influencer workflows, and listening tools.",
    icon: "Workflow",
    color: "from-teal-500 to-cyan-400",
  },
  Design: {
    description: "Graphic design, brand kits, templates, visual collaboration, and asset tools.",
    icon: "Image",
    color: "from-pink-500 to-rose-400",
  },
  Presentation: {
    description: "Deck creation, slide generation, storytelling, and presentation design tools.",
    icon: "Sparkles",
    color: "from-yellow-500 to-orange-400",
  },
  Education: {
    description: "Tutoring, course creation, student support, and learning productivity tools.",
    icon: "Brain",
    color: "from-blue-600 to-indigo-500",
  },
  "Resume / Career": {
    description: "Resume writing, interview prep, job search, and career workflow tools.",
    icon: "Sparkles",
    color: "from-zinc-700 to-slate-500",
  },
  Automation: {
    description: "Workflow automation, agents, integrations, scraping, and orchestration tools.",
    icon: "Workflow",
    color: "from-green-500 to-emerald-400",
  },
  "Business / CRM": {
    description: "CRM, sales ops, enterprise workflows, legal, and business intelligence tools.",
    icon: "Bot",
    color: "from-neutral-700 to-zinc-500",
  },
  Analytics: {
    description: "Audience analytics, listening, insights, attribution, and measurement tools.",
    icon: "SearchCheck",
    color: "from-slate-600 to-slate-400",
  },
  "Avatar / Video Avatar": {
    description: "Talking avatars, presenter videos, synthetic spokespeople, and persona tools.",
    icon: "Bot",
    color: "from-purple-500 to-fuchsia-400",
  },
  Advertising: {
    description: "Ad creative generation, media buying intelligence, and campaign automation tools.",
    icon: "Megaphone",
    color: "from-amber-500 to-yellow-400",
  },
};

export const narrowToBroadCategoryMap = {
  "Conversational AI": "Writing",
  "Long Context Assistant": "Writing",
  "Multimodal Workspace": "Productivity",
  "Brand Copywriting": "Writing",
  "Outbound Sales AI": "Marketing",
  "SEO Content Writing": "SEO",
  "Quick Draft Generator": "Writing",
  "Creative Storytelling": "Writing",
  "Knowledge Workspace": "Productivity",
  "Writing Improvement": "Writing",
  "Art Generation": "Image Generation",
  "Visual Concept Design": "Image Generation",
  "Game Asset Creation": "Image Generation",
  "Creative Suite AI": "Design",
  "Visual Productivity": "Design",
  "Typography Image Design": "Image Generation",
  "Generative Video": "Video Editing",
  "Short Video Creation": "Video Editing",
  "Training Avatar Video": "Avatar / Video Avatar",
  "Localized Presenter Video": "Avatar / Video Avatar",
  "Transcript Editing": "Video Editing",
  "Voice Synthesis": "Audio / Voice",
  "Commercial Voiceover": "Audio / Voice",
  "Voice API Platform": "Audio / Voice",
  "Meeting Notes": "Productivity",
  "Meeting Intelligence": "Productivity",
  "Answer Engine Search": "Research",
  "Research Paper Analysis": "Research",
  "Scientific Search": "Research",
  "Citation Verification": "Research",
  "Code Completion": "Coding",
  "AI Code Editor": "Coding",
  "Developer Autocomplete": "Coding",
  "Private Coding Assistant": "Coding",
  "Browser App Builder": "Coding",
  "Developer Search": "Coding",
  "UI Code Generation": "Coding",
  "Website Generation": "Design",
  "Wireframe Builder": "Design",
  "Product UI Design": "Design",
  "Narrative Slides": "Presentation",
  "Document Presentation": "Presentation",
  "Smart Deck Design": "Presentation",
  "Collaborative Decks": "Presentation",
  "Outline To Slides": "Presentation",
  "Pitch Automation": "Presentation",
  "Workflow Automation": "Automation",
  "Scenario Automation": "Automation",
  "Ops Orchestration": "Automation",
  "AI Team Workspace": "Productivity",
  "Smart Notes": "Productivity",
  "Calendar Scheduling AI": "Productivity",
  "Project Management AI": "Productivity",
  "Structured Operations AI": "Business / CRM",
  "CRM Content Assistant": "Business / CRM",
  "Enterprise CRM Intelligence": "Business / CRM",
  "Sales Pipeline AI": "Business / CRM",
  "Content Optimization": "SEO",
  "Competitive SEO Research": "SEO",
  "Backlink Intelligence": "SEO",
  "SERP Content Scoring": "SEO",
  "Automated SEO Deployment": "SEO",
  "Content Authenticity": "SEO",
  "Social Caption Studio": "Social Media",
  "Social Creative Engine": "Social Media",
  "Social Scheduling AI": "Social Media",
  "Content Planning Assistant": "Social Media",
  "Content Repurposing": "Social Media",
  "Social Listening": "Analytics",
  "Support Chat Automation": "Chatbots",
  "Lead Qualification Chat": "Chatbots",
  "Ecommerce Chat Support": "Chatbots",
  "Messaging Automation": "Chatbots",
  "Bot Development Platform": "Chatbots",
  "Agent Conversation Design": "Chatbots",
  "AI Music Composition": "Audio / Voice",
  "Royalty-Free Music": "Audio / Voice",
  "Instant Song Creation": "Audio / Voice",
  "Mood Soundtrack Builder": "Audio / Voice",
  "Live Audio Generation": "Audio / Voice",
  "Voice Cloning API": "Audio / Voice",
  "Voice Studio": "Audio / Voice",
  "Speech Intelligence API": "Audio / Voice",
  "Real-Time Speech Recognition": "Audio / Voice",
  "Multilingual Transcription": "Audio / Voice",
  "Career Tracking": "Resume / Career",
  "Resume Builder": "Resume / Career",
  "Resume Scoring": "Resume / Career",
  "Job Hunt CRM": "Resume / Career",
  "Interview Copilot": "Resume / Career",
  "Tutor Assistant": "Education",
  "Quiz Generator": "Education",
  "Student Homework Help": "Education",
  "Course Builder": "Education",
  "Teacher Workflow Assistant": "Education",
  "AI Tool Discovery": "Research",
  "Enterprise Knowledge Search": "Business / CRM",
  "Legal AI Assistant": "Business / CRM",
  "Meeting Highlights": "Productivity",
  "Web Data Extraction": "Automation",
  "Social Media Management": "Social Media",
  "Social Content Scheduling": "Social Media",
  "Enterprise Social Suite": "Social Media",
  "Visual Social Scheduling": "Social Media",
  "Content Recycling": "Social Media",
  "Social Post Generation": "Social Media",
  "Social Publishing Hub": "Social Media",
  "Social Content Ops": "Social Media",
  "Social Calendar Collaboration": "Social Media",
  "Agency Social Management": "Social Media",
  "Social Analytics Planner": "Analytics",
  "Unified Social Inbox": "Social Media",
  "Creator Social Planner": "Social Media",
  "Pinterest Instagram Growth": "Social Media",
  "LinkedIn X Writing": "Social Media",
  "LinkedIn Growth Assistant": "Social Media",
  "X Growth Automation": "Social Media",
  "Hashtag Strategy": "Social Media",
  "Hashtag Research": "Social Media",
  "Real-Time Hashtags": "Social Media",
  "Instagram Growth Toolkit": "Social Media",
  "Influencer Engagement Metrics": "Analytics",
  "Influencer Discovery": "Social Media",
  "Creator Commerce Platform": "Social Media",
  "Creator Database Search": "Social Media",
  "Influencer Search Engine": "Social Media",
  "Online Mention Tracking": "Analytics",
  "Brand Monitoring": "Analytics",
  "Web Listening Analytics": "Analytics",
  "Consumer Intelligence": "Analytics",
  "Market Intelligence": "Analytics",
  "Customer Experience Social": "Analytics",
  "SMB Social Suite": "Social Media",
  "Inbox And Publishing": "Social Media",
  "Agency Scheduling": "Social Media",
  "Content Discovery Scheduler": "Social Media",
  "Marketing Calendar": "Marketing",
  "Evergreen Queue Automation": "Social Media",
  "Visual Publishing Workflow": "Social Media",
  "Social Performance Analytics": "Analytics",
  "Content Distribution": "Marketing",
  "Enterprise Community Social": "Social Media",
  "B2B Social Management": "Social Media",
  "Moderation Automation": "Social Media",
  "Social Team Collaboration": "Social Media",
  "Brand Asset Automation": "Design",
  "AI Creative Design": "Design",
  "Quick Brand Design": "Design",
  "Social Graphic Templates": "Design",
  "Visual Template Design": "Design",
  "Browser Video Editing": "Video Editing",
  "Marketing Video Maker": "Video Editing",
  "Article To Video": "Video Editing",
  "Content Repurposing Video": "Video Editing",
  "Template Video Creation": "Video Editing",
  "Video Marketing Suite": "Video Editing",
  "Creative Video AI": "Video Editing",
  "Online Video Editor": "Video Editing",
  "Simple Video Builder": "Video Editing",
  "Talking Avatar Studio": "Avatar / Video Avatar",
  "Personalized Video AI": "Avatar / Video Avatar",
  "Avatar Lesson Videos": "Avatar / Video Avatar",
  "Animated Video Generator": "Video Editing",
  "Creative Automation Suite": "Design",
  "Marketing Design Workspace": "Design",
  "Marketing Copy Platform": "Writing",
  "Ecommerce Product Writing": "Writing",
  "Performance Copy Optimization": "Writing",
  "Content Drafting Assistant": "Writing",
  "Content Brief Generator": "SEO",
  "Sales Copy Generation": "Writing",
  "Outreach Campaign Automation": "Marketing",
  "Ad Campaign Automation": "Advertising",
  "Ad Creative Generation": "Advertising",
  "Ad Creative Assistant": "Advertising",
  "Ad Asset Production": "Advertising",
  "Display Ad Production": "Advertising",
  "Media Buying Intelligence": "Advertising",
  "Ad Rules Automation": "Advertising",
  "Autonomous Ad Optimization": "Advertising",
  "Cold Outreach Personalization": "Marketing",
  "Lead Data Automation": "Automation",
  "Growth Automation Toolkit": "Automation",
  "LinkedIn Prospecting": "Marketing",
  "LinkedIn Campaign Automation": "Marketing",
  "Safe LinkedIn Outreach": "Marketing",
  "Lead Capture Automation": "Marketing",
  "Messenger Automation": "Chatbots",
  "No-Code Messenger Bot": "Chatbots",
  "Omnichannel Chatbot Builder": "Chatbots",
  "AI Support Resolution": "Chatbots",
  "Customer Service AI": "Chatbots",
  "Conversational Support AI": "Chatbots",
};

export const normalizeCategory = (category) => narrowToBroadCategoryMap[category] || category;

export const broadCategories = Object.entries(categoryDefinitions).map(([name, config]) => ({
  name,
  slug: createSlug(name),
  description: config.description,
  icon: config.icon,
  color: config.color,
}));
