import { createSlug } from "../utils/createSlug.js";
import { broadCategories, normalizeCategory } from "./categoryTaxonomy.js";

const toolEntries = [
  ["ChatGPT", "Conversational AI", "Free Trial", "Conversational AI for drafting, brainstorming, and research support."],
  ["Claude", "Long Context Assistant", "Free Trial", "Context-rich assistant for analysis, ideation, and document workflows."],
  ["Gemini", "Multimodal Workspace", "Free Trial", "Multimodal workspace assistant for planning and quick execution."],
  ["Jasper", "Brand Copywriting", "Paid", "Brand-focused AI copy platform for campaigns and ad creative."],
  ["Copy.ai", "Outbound Sales AI", "Free Trial", "Sales and marketing workflows for outreach and content production."],
  ["Writesonic", "SEO Content Writing", "Free Trial", "SEO-friendly content generation for blogs, ads, and landing pages."],
  ["Rytr", "Quick Draft Generator", "Free Trial", "Lightweight AI writing tool for ideas, posts, and email drafts."],
  ["Sudowrite", "Creative Storytelling", "Paid", "Creative writing companion for fiction authors and storytellers."],
  ["Notion AI", "Knowledge Workspace", "Paid", "Knowledge base assistant for notes, docs, and team planning."],
  ["GrammarlyGO", "Writing Improvement", "Free Trial", "Rewrite and tone assistant for polished communication."],
  ["Midjourney", "Art Generation", "Paid", "Prompt-driven art generation for concept visuals and branding."],
  ["DALL-E", "Visual Concept Design", "Paid", "Generate illustrations, mockups, and scene compositions from text."],
  ["Leonardo AI", "Game Asset Creation", "Free Trial", "Visual creation suite for assets, game art, and marketing design."],
  ["Adobe Firefly", "Creative Suite AI", "Free Trial", "Generative design features for creative workflows and assets."],
  ["Canva Magic Studio", "Visual Productivity", "Free Trial", "AI-powered creative assistant for social, docs, and presentations."],
  ["Ideogram", "Typography Image Design", "Free Trial", "Text-accurate image generation for posters and brand concepts."],
  ["Runway", "Generative Video", "Paid", "Generative video editing, motion design, and scene generation."],
  ["Pika", "Short Video Creation", "Free Trial", "Fast AI video creation for social clips and animated ideas."],
  ["Synthesia", "Training Avatar Video", "Paid", "Studio for avatar-led explainers, onboarding, and training videos."],
  ["HeyGen", "Localized Presenter Video", "Paid", "Create talking presenter videos with templates and localization."],
  ["Descript", "Transcript Editing", "Free Trial", "Transcript-based editing for podcasts, videos, and meetings."],
  ["ElevenLabs", "Voice Synthesis", "Free Trial", "Voice generation, dubbing, and expressive narration tools."],
  ["Murf", "Commercial Voiceover", "Paid", "Voiceover platform for product demos, ads, and education content."],
  ["PlayHT", "Voice API Platform", "Paid", "API-first voice synthesis and cloned speech for applications."],
  ["Otter", "Meeting Notes", "Free Trial", "Meeting transcription, summaries, and searchable notes."],
  ["Fireflies", "Meeting Intelligence", "Free Trial", "AI notetaker for meetings with action items and search."],
  ["Perplexity", "Answer Engine Search", "Free Trial", "Answer engine with cited search results and research summaries."],
  ["Elicit", "Research Paper Analysis", "Free Trial", "Research assistant for literature reviews and evidence collection."],
  ["Consensus", "Scientific Search", "Free Trial", "Academic search and scientific answer summaries."],
  ["Scite", "Citation Verification", "Paid", "Citation-aware research discovery and paper evaluation."],
  ["GitHub Copilot", "Code Completion", "Paid", "AI pair programmer for code generation and inline suggestions."],
  ["Cursor", "AI Code Editor", "Free Trial", "AI-first code editor with repo-aware chat and refactoring."],
  ["Codeium", "Developer Autocomplete", "Free Trial", "Autocomplete and AI coding support across editors."],
  ["Tabnine", "Private Coding Assistant", "Paid", "Private code assistance for enterprise development teams."],
  ["Replit AI", "Browser App Builder", "Free Trial", "Build and ship apps faster from the browser."],
  ["Phind", "Developer Search", "Free Trial", "Developer search and technical Q&A optimized for coding."],
  ["V0", "UI Code Generation", "Free Trial", "Prompt-based UI generation for modern React frontends."],
  ["Framer AI", "Website Generation", "Free Trial", "Rapid website generation and content assistance for landing pages."],
  ["Uizard", "Wireframe Builder", "Free Trial", "Convert ideas into wireframes and product mockups quickly."],
  ["Galileo AI", "Product UI Design", "Paid", "Generate polished UI screens from prompts and intent."],
  ["Tome", "Narrative Slides", "Free Trial", "Narrative slide creation with generated storytelling blocks."],
  ["Gamma", "Document Presentation", "Free Trial", "Presentations, docs, and webpages created from simple prompts."],
  ["Beautiful.ai", "Smart Deck Design", "Paid", "Smart slide builder with design assistance and templates."],
  ["Pitch", "Collaborative Decks", "Free Trial", "Collaborative pitch deck creation with AI writing support."],
  ["SlidesAI", "Outline To Slides", "Free Trial", "Turn outlines and docs into presentation decks."],
  ["Decktopus", "Pitch Automation", "Paid", "Guided pitch creation with automatic slide design."],
  ["Zapier AI", "Workflow Automation", "Free Trial", "Workflow automation with natural-language setup assistance."],
  ["Make AI", "Scenario Automation", "Free Trial", "Scenario builder for AI-powered automations and integrations."],
  ["n8n AI", "Ops Orchestration", "Free Trial", "Flexible workflow orchestration for ops and internal tools."],
  ["Taskade AI", "AI Team Workspace", "Free Trial", "Collaborative workspaces with AI agents, docs, and tasks."],
  ["Mem", "Smart Notes", "Paid", "AI-powered note organization and contextual retrieval."],
  ["Motion", "Calendar Scheduling AI", "Paid", "Calendar and task scheduling assistant for deep work planning."],
  ["ClickUp AI", "Project Management AI", "Paid", "Project management platform with AI docs and task creation."],
  ["Airtable AI", "Structured Operations AI", "Paid", "Structured workflows with AI fields, summaries, and automations."],
  ["HubSpot AI", "CRM Content Assistant", "Free Trial", "CRM workflows with AI content and customer ops support."],
  ["Salesforce Einstein", "Enterprise CRM Intelligence", "Paid", "Enterprise AI for CRM insights, forecasting, and service."],
  ["Pipedrive AI", "Sales Pipeline AI", "Paid", "Pipeline support and assistant features for revenue teams."],
  ["Surfer SEO", "Content Optimization", "Paid", "Optimize content with keyword scoring and structure insights."],
  ["Semrush AI", "Competitive SEO Research", "Paid", "Competitive research, SEO briefs, and organic growth tooling."],
  ["Ahrefs AI", "Backlink Intelligence", "Paid", "Keyword, backlink, and content optimization support."],
  ["NeuronWriter", "SERP Content Scoring", "Paid", "Content optimization with SERP-driven recommendations."],
  ["Alli AI", "Automated SEO Deployment", "Paid", "Automated SEO deployment and optimization at scale."],
  ["Originality AI", "Content Authenticity", "Paid", "Content quality, AI detection, and plagiarism workflows."],
  ["Ocoya", "Social Caption Studio", "Paid", "Generate captions, creatives, and schedule social content."],
  ["Predis.ai", "Social Creative Engine", "Free Trial", "AI social media content engine for posts and reels."],
  ["Publer AI", "Social Scheduling AI", "Free Trial", "Social scheduling and caption generation for teams."],
  ["Buffer AI Assistant", "Content Planning Assistant", "Free Trial", "Content drafting and planning inside social workflows."],
  ["Lately", "Content Repurposing", "Paid", "Repurpose long-form content into social-ready campaigns."],
  ["Brand24 AI", "Social Listening", "Paid", "Monitor mentions, sentiment, and market conversations."],
  ["Intercom Fin", "Support Chat Automation", "Paid", "Support chatbot built for automated customer resolution."],
  ["Drift", "Lead Qualification Chat", "Paid", "Conversational marketing and qualification bot for websites."],
  ["Tidio AI", "Ecommerce Chat Support", "Free Trial", "Live chat plus AI assistance for ecommerce and support."],
  ["ManyChat AI", "Messaging Automation", "Free Trial", "Messaging automation for WhatsApp, Instagram, and Messenger."],
  ["Botpress", "Bot Development Platform", "Free Trial", "Developer-friendly platform for custom AI assistants."],
  ["Voiceflow", "Agent Conversation Design", "Free Trial", "Collaborative chatbot and agent design environment."],
  ["AIVA", "AI Music Composition", "Free Trial", "Compose background music and emotion-based soundtracks."],
  ["Soundraw", "Royalty-Free Music", "Paid", "Generate royalty-safe music for video and branded content."],
  ["Boomy", "Instant Song Creation", "Free Trial", "Create songs quickly for streaming, demos, and social media."],
  ["Beatoven", "Mood Soundtrack Builder", "Free Trial", "Background music generation tuned to content mood and pace."],
  ["Mubert", "Live Audio Generation", "Free Trial", "AI music generation for creators, apps, and live content."],
  ["Resemble AI", "Voice Cloning API", "Paid", "Voice cloning APIs for conversational and enterprise products."],
  ["Lovo", "Voice Studio", "Free Trial", "Text-to-speech voice generation with studio workflows."],
  ["AssemblyAI", "Speech Intelligence API", "Paid", "Speech AI APIs for transcription, moderation, and insights."],
  ["Deepgram", "Real-Time Speech Recognition", "Paid", "Speech recognition APIs for real-time and recorded audio."],
  ["Whisper API", "Multilingual Transcription", "Paid", "Multilingual transcription and translation pipeline support."],
  ["Teal", "Career Tracking", "Free Trial", "Job tracker and resume tailoring toolkit for candidates."],
  ["Kickresume", "Resume Builder", "Free Trial", "Resume and cover letter generation with ready templates."],
  ["Resume Worded", "Resume Scoring", "Free Trial", "Score resumes and improve job application positioning."],
  ["Huntr", "Job Hunt CRM", "Free Trial", "Track applications and refine AI-generated resumes."],
  ["Final Round AI", "Interview Copilot", "Paid", "Interview copilot and prep platform for job seekers."],
  ["Khanmigo", "Tutor Assistant", "Paid", "Learning assistant for tutoring and guided practice."],
  ["Quizgecko", "Quiz Generator", "Free Trial", "Create quizzes, flashcards, and study guides from content."],
  ["Socratic", "Student Homework Help", "Free", "Student help assistant for solving and understanding topics."],
  ["Coursebox AI", "Course Builder", "Paid", "Build lessons, course outlines, and assessments quickly."],
  ["TeachmateAI", "Teacher Workflow Assistant", "Paid", "Teacher support for worksheets, planning, and classroom content."],
  ["FutureTools", "AI Tool Discovery", "Free", "AI tools discovery and launch tracking platform."],
  ["Glean", "Enterprise Knowledge Search", "Paid", "Enterprise knowledge search across apps and documents."],
  ["Harvey", "Legal AI Assistant", "Paid", "Legal and professional services assistant for complex workflows."],
  ["Tactiq", "Meeting Highlights", "Free Trial", "Meeting notes, highlights, and AI action items."],
  ["Browse AI", "Web Data Extraction", "Paid", "No-code web data extraction and monitoring."],
  ["Hootsuite AI", "Social Media Management", "Free Trial", "Social publishing, listening, and scheduling workflows with AI assistance."],
  ["Buffer AI", "Social Content Scheduling", "Free", "Create and schedule social content with lightweight AI help for teams and creators."],
  ["Sprout Social", "Enterprise Social Suite", "Paid", "Enterprise social media management, analytics, and engagement workflows."],
  ["Later", "Visual Social Scheduling", "Free Trial", "Plan social calendars, link-in-bio, and content timing across channels."],
  ["SocialBee", "Content Recycling", "Free Trial", "Organize, recycle, and publish social posts from one workspace."],
  ["Predis AI", "Social Post Generation", "Free Trial", "Generate social creatives, captions, and ad-ready ideas faster."],
  ["Publer", "Social Publishing Hub", "Free Trial", "Multi-channel publishing, approval flows, and social queue management."],
  ["ContentStudio", "Social Content Ops", "Free Trial", "Discover, plan, and publish content across social and blogs."],
  ["Loomly", "Social Calendar Collaboration", "Free Trial", "Collaborative social calendar with content planning and approvals."],
  ["Sendible", "Agency Social Management", "Paid", "Agency-focused social scheduling, inboxes, and client reporting."],
  ["Metricool", "Social Analytics Planner", "Free", "Track analytics, schedule posts, and monitor campaigns in one dashboard."],
  ["Vista Social", "Unified Social Inbox", "Free Trial", "Publishing, engagement, and listening workflows for modern brands."],
  ["Planoly", "Creator Social Planner", "Free Trial", "Visual social planning and commerce-ready creator workflows."],
  ["Tailwind", "Pinterest Instagram Growth", "Free Trial", "Content planning and performance insights for visual platforms."],
  ["Postwise", "LinkedIn X Writing", "Free Trial", "Write faster viral social posts for X and LinkedIn."],
  ["Taplio", "LinkedIn Growth Assistant", "Free Trial", "LinkedIn content ideas, scheduling, and creator analytics."],
  ["TweetHunter", "X Growth Automation", "Free Trial", "Generate, schedule, and repurpose posts for X audiences."],
  ["Flick AI", "Hashtag Strategy", "Free Trial", "Caption generation, hashtag research, and content planning for creators."],
  ["Hashtagify", "Hashtag Research", "Free Trial", "Discover trending hashtags and topic clusters for social campaigns."],
  ["RiteTag", "Real-Time Hashtags", "Free Trial", "Real-time hashtag suggestions for stronger post reach."],
  ["Inflact", "Instagram Growth Toolkit", "Paid", "Instagram-focused analytics, scheduling, and engagement tools."],
  ["Phlanx", "Influencer Engagement Metrics", "Free Trial", "Measure influencer engagement and benchmark creator profiles."],
  ["TrendHERO", "Influencer Discovery", "Free Trial", "Find, evaluate, and track influencers with audience quality insights."],
  ["Upfluence", "Creator Commerce Platform", "Paid", "End-to-end influencer and affiliate relationship management."],
  ["Modash", "Creator Database Search", "Paid", "Discover creators and evaluate campaign-fit audience data."],
  ["Heepsy", "Influencer Search Engine", "Free Trial", "Search and filter creators for outreach and partnerships."],
  ["Brand24", "Online Mention Tracking", "Free Trial", "Track brand mentions, sentiment, and emerging conversations online."],
  ["Mention", "Brand Monitoring", "Free Trial", "Monitor social and web mentions with alerts and listening tools."],
  ["Awario", "Web Listening Analytics", "Free Trial", "Social listening and sentiment analysis for brands and agencies."],
  ["Brandwatch", "Consumer Intelligence", "Paid", "Enterprise consumer intelligence and social listening at scale."],
  ["Talkwalker", "Market Intelligence", "Paid", "AI-powered social listening, analytics, and brand intelligence."],
  ["Emplifi", "Customer Experience Social", "Paid", "Enterprise CX and social media platform for care, commerce, and content."],
  ["Zoho Social", "SMB Social Suite", "Free Trial", "Social scheduling, monitoring, and reporting for small businesses."],
  ["Agorapulse", "Inbox And Publishing", "Free Trial", "Manage publishing, comments, and reporting from a unified inbox."],
  ["SocialPilot", "Agency Scheduling", "Free Trial", "Bulk scheduling, analytics, and client-ready reporting for agencies."],
  ["Crowdfire", "Content Discovery Scheduler", "Free", "Discover articles and schedule social content across profiles."],
  ["CoSchedule", "Marketing Calendar", "Free Trial", "Marketing planning, social scheduling, and campaign calendar management."],
  ["MeetEdgar", "Evergreen Queue Automation", "Paid", "Recycle evergreen content automatically across social channels."],
  ["Sked Social", "Visual Publishing Workflow", "Paid", "Plan visual-first social campaigns with approvals and tagging."],
  ["Iconosquare", "Social Performance Analytics", "Paid", "Analytics, reporting, and content performance tracking for social teams."],
  ["StoryChief", "Content Distribution", "Free Trial", "Publish and distribute content across channels from one editor."],
  ["Khoros", "Enterprise Community Social", "Paid", "Enterprise social care, communities, and digital engagement workflows."],
  ["Oktopost", "B2B Social Management", "Paid", "B2B social publishing, employee advocacy, and attribution analytics."],
  ["NapoleonCat", "Moderation Automation", "Free Trial", "Moderate comments, messages, and social conversations with automation."],
  ["Statusbrew", "Social Team Collaboration", "Free Trial", "Social publishing, engagement, and team workflows for brands."],
  ["RelayThat", "Brand Asset Automation", "Free Trial", "Generate on-brand creative assets for ads and social campaigns."],
  ["Canva AI", "AI Creative Design", "Free Trial", "Design social graphics and presentations with AI-assisted creation."],
  ["Adobe Express AI", "Quick Brand Design", "Free Trial", "Fast AI-powered designs for social posts, flyers, and brand content."],
  ["VistaCreate", "Social Graphic Templates", "Free Trial", "Create branded social visuals with templates and animation tools."],
  ["Crello", "Visual Template Design", "Free Trial", "Template-based graphic design for social and marketing content."],
  ["Kapwing", "Browser Video Editing", "Free Trial", "Collaborative browser-based video editor with AI workflows."],
  ["InVideo", "Marketing Video Maker", "Free Trial", "Turn scripts and prompts into marketing videos and social clips."],
  ["Pictory", "Article To Video", "Free Trial", "Turn long-form text into video summaries and short content."],
  ["Lumen5", "Content Repurposing Video", "Free Trial", "Convert articles and blog content into video stories."],
  ["Animoto", "Template Video Creation", "Free Trial", "Make simple marketing videos with drag-and-drop scenes."],
  ["Wave.video", "Video Marketing Suite", "Free Trial", "Create, host, and repurpose video content for campaigns."],
  ["Runway ML", "Creative Video AI", "Paid", "Generative video and editing toolkit for creators and teams."],
  ["VEED IO", "Online Video Editor", "Free Trial", "Edit, subtitle, and repurpose video content in the browser."],
  ["FlexClip", "Simple Video Builder", "Free Trial", "Create videos quickly with templates, media, and AI tools."],
  ["D-ID", "Talking Avatar Studio", "Free Trial", "Generate talking avatars and presenter videos from scripts."],
  ["Rephrase AI", "Personalized Video AI", "Paid", "Create synthetic spokesperson videos for sales and marketing."],
  ["Elai.io", "Avatar Lesson Videos", "Free Trial", "Build avatar-led explainer and training videos without filming."],
  ["Steve AI", "Animated Video Generator", "Free Trial", "Create animated videos from text with templates and scenes."],
  ["Designs.ai", "Creative Automation Suite", "Free Trial", "Generate logos, videos, voiceovers, and brand assets from one suite."],
  ["Simplified", "Marketing Design Workspace", "Free Trial", "Social design, copywriting, video, and publishing workflows in one app."],
  ["Jasper AI", "Marketing Copy Platform", "Paid", "Brand-safe AI writing workflows for campaigns, ads, and product marketing."],
  ["Hypotenuse AI", "Ecommerce Product Writing", "Free Trial", "Generate product descriptions, category copy, and SEO content at scale."],
  ["Anyword", "Performance Copy Optimization", "Free Trial", "Create conversion-focused copy with predictive performance insights."],
  ["Peppertype AI", "Content Drafting Assistant", "Free Trial", "Generate quick content ideas, social copy, and marketing drafts."],
  ["NeuralText", "Content Brief Generator", "Free Trial", "Create SEO content briefs and optimize pages with SERP data."],
  ["ClosersCopy", "Sales Copy Generation", "Paid", "Long-form and direct-response copywriting assistance for marketers."],
  ["Postaga", "Outreach Campaign Automation", "Free Trial", "Automate outreach workflows for PR, backlinks, and partnerships."],
  ["Smartly.io", "Ad Campaign Automation", "Paid", "Scale ad creation, media buying, and creative testing across channels."],
  ["AdCreative.ai", "Ad Creative Generation", "Free Trial", "Generate ad creatives and copy variants for paid campaigns."],
  ["Predis.ai Ads", "Ad Creative Assistant", "Free Trial", "Generate ad-ready creatives and captions for paid social."],
  ["Quickads AI", "Ad Asset Production", "Free Trial", "Produce ad assets and creative variations faster for marketers."],
  ["Creatopy", "Display Ad Production", "Free Trial", "Design and scale display ads and campaign creatives efficiently."],
  ["Madgicx", "Media Buying Intelligence", "Paid", "AI-driven ad optimization and audience insights for growth teams."],
  ["Revealbot", "Ad Rules Automation", "Paid", "Automate paid campaign management with rule-based workflows."],
  ["Trapica", "Autonomous Ad Optimization", "Paid", "AI bidding and optimization for performance marketing campaigns."],
  ["Smartwriter AI", "Cold Outreach Personalization", "Free Trial", "Personalize outbound emails, LinkedIn outreach, and pitches."],
  ["PhantomBuster", "Lead Data Automation", "Free Trial", "Automate lead collection and social scraping workflows."],
  ["TexAu", "Growth Automation Toolkit", "Free Trial", "Run lead generation and outreach automation across platforms."],
  ["Zopto", "LinkedIn Prospecting", "Paid", "LinkedIn automation and outreach for B2B prospecting teams."],
  ["MeetAlfred", "LinkedIn Campaign Automation", "Free Trial", "Automate LinkedIn outreach and sequence-based follow-up."],
  ["Expandi", "Safe LinkedIn Outreach", "Paid", "LinkedIn outreach platform built for personalization and deliverability."],
  ["Driftrock", "Lead Capture Automation", "Paid", "Connect paid social lead generation with CRM and automation pipelines."],
  ["ManyChat", "Messenger Automation", "Free Trial", "Automate conversations on Instagram, WhatsApp, and Messenger."],
  ["Chatfuel", "No-Code Messenger Bot", "Free Trial", "Build chat automations and sales flows without code."],
  ["MobileMonkey", "Omnichannel Chatbot Builder", "Free Trial", "Create marketing chatbots across web, SMS, and messaging apps."],
  ["Intercom AI", "AI Support Resolution", "Paid", "Use AI agents and inbox tools to resolve support faster."],
  ["Zendesk AI", "Customer Service AI", "Paid", "AI-powered support automation, routing, and service insights."],
  ["Freshchat AI", "Conversational Support AI", "Free Trial", "Support teams with AI-assisted chat, bots, and agent workflows."],
];

const websiteUrlMap = {
  "ChatGPT": "https://openai.com/chatgpt",
  Claude: "https://www.anthropic.com/claude",
  Gemini: "https://gemini.google.com",
  Jasper: "https://www.jasper.ai",
  "Copy.ai": "https://www.copy.ai",
  Writesonic: "https://writesonic.com",
  Rytr: "https://rytr.me",
  Sudowrite: "https://www.sudowrite.com",
  "Notion AI": "https://www.notion.so/product/ai",
  GrammarlyGO: "https://www.grammarly.com/grammarlygo",
  Midjourney: "https://www.midjourney.com",
  "DALL-E": "https://openai.com/dall-e-3",
  "Leonardo AI": "https://leonardo.ai",
  "Adobe Firefly": "https://www.adobe.com/products/firefly.html",
  "Canva Magic Studio": "https://www.canva.com/magic-studio",
  Ideogram: "https://ideogram.ai",
  Runway: "https://runwayml.com",
  Pika: "https://pika.art",
  Synthesia: "https://www.synthesia.io",
  HeyGen: "https://www.heygen.com",
  Descript: "https://www.descript.com",
  ElevenLabs: "https://elevenlabs.io",
  Murf: "https://murf.ai",
  PlayHT: "https://play.ht",
  Otter: "https://otter.ai",
  Fireflies: "https://fireflies.ai",
  Perplexity: "https://www.perplexity.ai",
  Elicit: "https://elicit.com",
  Consensus: "https://consensus.app",
  Scite: "https://scite.ai",
  "GitHub Copilot": "https://github.com/features/copilot",
  Cursor: "https://www.cursor.com",
  Codeium: "https://codeium.com",
  Tabnine: "https://www.tabnine.com",
  "Replit AI": "https://replit.com/ai",
  Phind: "https://www.phind.com",
  V0: "https://v0.dev",
  "Framer AI": "https://www.framer.com/ai",
  Uizard: "https://uizard.io",
  "Galileo AI": "https://www.usegalileo.ai",
  Tome: "https://tome.app",
  Gamma: "https://gamma.app",
  "Beautiful.ai": "https://www.beautiful.ai",
  Pitch: "https://pitch.com",
  SlidesAI: "https://www.slidesai.io",
  Decktopus: "https://www.decktopus.com",
  "Zapier AI": "https://zapier.com/ai",
  "Make AI": "https://www.make.com/en/ai",
  "n8n AI": "https://n8n.io",
  "Taskade AI": "https://www.taskade.com/ai",
  Mem: "https://mem.ai",
  Motion: "https://www.usemotion.com",
  "ClickUp AI": "https://clickup.com/ai",
  "Airtable AI": "https://www.airtable.com/platform/ai",
  "HubSpot AI": "https://www.hubspot.com/artificial-intelligence",
  "Salesforce Einstein": "https://www.salesforce.com/products/einstein-ai-solutions",
  "Pipedrive AI": "https://www.pipedrive.com",
  "Surfer SEO": "https://surferseo.com",
  "Semrush AI": "https://www.semrush.com",
  "Ahrefs AI": "https://ahrefs.com",
  NeuronWriter: "https://neuronwriter.com",
  "Alli AI": "https://www.alliai.com",
  "Originality AI": "https://originality.ai",
  Ocoya: "https://www.ocoya.com",
  "Predis.ai": "https://predis.ai",
  "Publer AI": "https://publer.io",
  "Buffer AI Assistant": "https://buffer.com/ai-assistant",
  Lately: "https://www.lately.ai",
  "Brand24 AI": "https://brand24.com",
  "Hootsuite AI": "https://www.hootsuite.com",
  "Buffer AI": "https://buffer.com/ai-assistant",
  "Sprout Social": "https://sproutsocial.com",
  Later: "https://later.com",
  SocialBee: "https://socialbee.com",
  "Predis AI": "https://predis.ai",
  Publer: "https://publer.io",
  ContentStudio: "https://contentstudio.io",
  Loomly: "https://www.loomly.com",
  Sendible: "https://www.sendible.com",
  Metricool: "https://metricool.com",
  "Vista Social": "https://vistasocial.com",
  Planoly: "https://www.planoly.com",
  Tailwind: "https://www.tailwindapp.com",
  Postwise: "https://postwise.ai",
  Taplio: "https://taplio.com",
  TweetHunter: "https://tweethunter.io",
  "Flick AI": "https://flick.social",
  Hashtagify: "https://hashtagify.me",
  RiteTag: "https://ritetag.com",
  Inflact: "https://inflact.com",
  Phlanx: "https://phlanx.com",
  TrendHERO: "https://trendhero.io",
  Upfluence: "https://www.upfluence.com",
  Modash: "https://www.modash.io",
  Heepsy: "https://www.heepsy.com",
  Brand24: "https://brand24.com",
  Mention: "https://mention.com",
  Awario: "https://awario.com",
  Brandwatch: "https://www.brandwatch.com",
  Talkwalker: "https://www.talkwalker.com",
  Emplifi: "https://emplifi.io",
  "Zoho Social": "https://www.zoho.com/social",
  Agorapulse: "https://www.agorapulse.com",
  SocialPilot: "https://www.socialpilot.co",
  Crowdfire: "https://www.crowdfireapp.com",
  CoSchedule: "https://coschedule.com",
  MeetEdgar: "https://meetedgar.com",
  "Sked Social": "https://skedsocial.com",
  Iconosquare: "https://www.iconosquare.com",
  StoryChief: "https://storychief.io",
  Khoros: "https://khoros.com",
  Oktopost: "https://www.oktopost.com",
  NapoleonCat: "https://napoleoncat.com",
  Statusbrew: "https://statusbrew.com",
  RelayThat: "https://relaythat.com",
  "Canva AI": "https://www.canva.com/ai-image-generator",
  "Adobe Express AI": "https://www.adobe.com/express",
  VistaCreate: "https://create.vista.com",
  Crello: "https://crello.com",
  Kapwing: "https://www.kapwing.com",
  InVideo: "https://invideo.io",
  Pictory: "https://pictory.ai",
  Lumen5: "https://lumen5.com",
  Animoto: "https://animoto.com",
  "Wave.video": "https://wave.video",
  "Runway ML": "https://runwayml.com",
  "VEED IO": "https://www.veed.io",
  FlexClip: "https://www.flexclip.com",
  "D-ID": "https://www.d-id.com",
  "Rephrase AI": "https://www.rephrase.ai",
  "Elai.io": "https://elai.io",
  "Steve AI": "https://www.steve.ai",
  "Designs.ai": "https://designs.ai",
  Simplified: "https://simplified.com",
  "Jasper AI": "https://www.jasper.ai",
  "Hypotenuse AI": "https://www.hypotenuse.ai",
  Anyword: "https://anyword.com",
  "Peppertype AI": "https://www.peppercontent.io/peppertype-ai",
  NeuralText: "https://neuraltext.com",
  ClosersCopy: "https://www.closerscopy.com",
  Postaga: "https://postaga.com",
  "Smartly.io": "https://www.smartly.io",
  "AdCreative.ai": "https://www.adcreative.ai",
  "Predis.ai Ads": "https://predis.ai",
  "Quickads AI": "https://quickads.ai",
  Creatopy: "https://www.creatopy.com",
  Madgicx: "https://madgicx.com",
  Revealbot: "https://revealbot.com",
  Trapica: "https://trapica.com",
  "Smartwriter AI": "https://www.smartwriter.ai",
  PhantomBuster: "https://phantombuster.com",
  TexAu: "https://texau.com",
  Zopto: "https://zopto.com",
  MeetAlfred: "https://meetalfred.com",
  Expandi: "https://expandi.io",
  Driftrock: "https://driftrock.com",
  ManyChat: "https://manychat.com",
  Chatfuel: "https://chatfuel.com",
  MobileMonkey: "https://mobilemonkey.com",
  "Intercom AI": "https://www.intercom.com/artificial-intelligence",
  "Zendesk AI": "https://www.zendesk.com/ai",
  "Freshchat AI": "https://www.freshworks.com/live-chat-software",
  "Intercom Fin": "https://www.intercom.com/fin",
  Drift: "https://www.drift.com",
  "Tidio AI": "https://www.tidio.com/lyro",
  "ManyChat AI": "https://manychat.com",
  Botpress: "https://botpress.com",
  Voiceflow: "https://www.voiceflow.com",
  AIVA: "https://www.aiva.ai",
  Soundraw: "https://soundraw.io",
  Boomy: "https://boomy.com",
  Beatoven: "https://www.beatoven.ai",
  Mubert: "https://mubert.com",
  "Resemble AI": "https://www.resemble.ai",
  Lovo: "https://lovo.ai",
  AssemblyAI: "https://www.assemblyai.com",
  Deepgram: "https://deepgram.com",
  "Whisper API": "https://openai.com/research/whisper",
  Teal: "https://www.tealhq.com",
  Kickresume: "https://www.kickresume.com",
  "Resume Worded": "https://resumeworded.com",
  Huntr: "https://huntr.co",
  "Final Round AI": "https://www.finalroundai.com",
  Khanmigo: "https://www.khanacademy.org/khan-labs",
  Quizgecko: "https://quizgecko.com",
  Socratic: "https://socratic.org",
  "Coursebox AI": "https://www.coursebox.ai",
  TeachmateAI: "https://teachmateai.com",
  FutureTools: "https://www.futuretools.io",
  Glean: "https://www.glean.com",
  Harvey: "https://www.harvey.ai",
  Tactiq: "https://tactiq.io",
  "Browse AI": "https://www.browse.ai",
};

const getLogoSeedUrl = (websiteUrl) => {
  const domain = new URL(websiteUrl).hostname.replace(/^www\./, "");
  return `https://unavatar.io/google/${domain}`;
};

const getAvatarLogoUrl = (name) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=0f172a&color=38bdf8&size=256&bold=true&format=png&rounded=true`;

const buildToolDocument = ({ name, category, pricing, description, websiteUrl, index, extraTags = [] }) => {
  const featured = index % 8 === 0 || index % 13 === 0;
  const normalizedCategory = normalizeCategory(category);
  const tags = [normalizedCategory, pricing, featured ? "Featured" : "Trending", "AI Tool", ...extraTags];

  if (normalizedCategory !== category) {
    tags.push(category);
  }

  return {
    name,
    slug: createSlug(name),
    description,
    longDescription: `${description} ${name} helps teams in the ${normalizedCategory.toLowerCase()} category move faster with cleaner workflows, stronger output quality, and scalable AI-powered execution.`,
    category: normalizedCategory,
    pricing,
    featured,
    websiteUrl,
    image: {
      url: websiteUrl ? getLogoSeedUrl(websiteUrl) : getAvatarLogoUrl(name),
      publicId: "",
    },
    tags: [...new Set(tags)].slice(0, 8),
    rating: Number((4.4 + ((index % 6) * 0.1)).toFixed(1)),
    monthlyVisits: `${(index + 3) * 11}K+`,
  };
};

const generatedCategoryConfig = {
  Writing: {
    stems: ["Write", "Copy", "Draft", "Script", "Story", "Content"],
    audiences: ["marketers", "writers", "founders", "content teams"],
    benefits: ["draft faster", "polish messaging", "turn ideas into clear content", "ship campaigns with less editing"],
  },
  "Image Generation": {
    stems: ["Canvas", "Pixel", "Render", "Vision", "Frame", "Art"],
    audiences: ["designers", "creators", "brand teams", "studios"],
    benefits: ["generate visuals quickly", "explore styles faster", "create branded assets", "mock up concepts without delay"],
  },
  "Video Editing": {
    stems: ["Video", "Motion", "Clip", "Reel", "Edit", "Studio"],
    audiences: ["video teams", "creators", "agencies", "social brands"],
    benefits: ["cut videos faster", "repurpose clips for social", "ship edits with less manual work", "turn footage into publish-ready content"],
  },
  "Audio / Voice": {
    stems: ["Voice", "Audio", "Beat", "Sound", "Speech", "Wave"],
    audiences: ["podcasters", "media teams", "educators", "apps"],
    benefits: ["generate voice and audio quickly", "polish spoken content", "build richer audio workflows", "launch speech experiences faster"],
  },
  Chatbots: {
    stems: ["Chat", "Agent", "Support", "Assist", "Reply", "Bot"],
    audiences: ["support teams", "operators", "businesses", "service teams"],
    benefits: ["answer users faster", "automate support flows", "route conversations cleanly", "launch helpful assistants quickly"],
  },
  Coding: {
    stems: ["Code", "Dev", "Build", "Stack", "Repo", "Deploy"],
    audiences: ["developers", "product teams", "engineers", "startups"],
    benefits: ["ship code faster", "clean up development workflows", "move from prompt to prototype", "speed up product delivery"],
  },
  Productivity: {
    stems: ["Task", "Note", "Flow", "Focus", "Desk", "Sprint"],
    audiences: ["operators", "teams", "founders", "knowledge workers"],
    benefits: ["stay organized", "summarize work faster", "keep projects moving", "reduce busywork across workflows"],
  },
  Research: {
    stems: ["Search", "Insight", "Query", "Source", "Proof", "Scout"],
    audiences: ["researchers", "analysts", "students", "knowledge teams"],
    benefits: ["find answers faster", "surface reliable sources", "speed up desk research", "turn questions into useful insights"],
  },
  SEO: {
    stems: ["Rank", "Keyword", "SERP", "Search", "Optimize", "Boost"],
    audiences: ["SEO teams", "content marketers", "agencies", "publishers"],
    benefits: ["grow organic traffic", "optimize content faster", "spot ranking opportunities", "improve search visibility"],
  },
  Marketing: {
    stems: ["Campaign", "Growth", "Lead", "Funnel", "Launch", "Reach"],
    audiences: ["growth teams", "marketers", "sales teams", "brands"],
    benefits: ["launch campaigns faster", "convert more demand", "personalize outreach", "scale marketing operations"],
  },
  "Social Media": {
    stems: ["Social", "Post", "Creator", "Trend", "Channel", "Viral"],
    audiences: ["creators", "social teams", "agencies", "brands"],
    benefits: ["plan posts faster", "grow channels", "turn ideas into social assets", "manage publishing with less friction"],
  },
  Design: {
    stems: ["Design", "Brand", "Layout", "UI", "Frame", "Creative"],
    audiences: ["design teams", "brands", "agencies", "product teams"],
    benefits: ["design assets quickly", "maintain visual consistency", "prototype ideas faster", "move from brief to polished creative"],
  },
  Presentation: {
    stems: ["Deck", "Slide", "Pitch", "Story", "Present", "Narrative"],
    audiences: ["founders", "sales teams", "consultants", "operators"],
    benefits: ["build decks quickly", "present ideas clearly", "polish slides without busywork", "turn notes into sharp presentations"],
  },
  Education: {
    stems: ["Tutor", "Learn", "Class", "Study", "Lesson", "Campus"],
    audiences: ["students", "teachers", "coaches", "training teams"],
    benefits: ["teach concepts clearly", "create learning content faster", "guide learners step by step", "build educational workflows quickly"],
  },
  "Resume / Career": {
    stems: ["Resume", "Career", "Interview", "Hire", "Talent", "CV"],
    audiences: ["job seekers", "career coaches", "students", "talent teams"],
    benefits: ["improve job search workflows", "prep faster for interviews", "tailor applications clearly", "present experience better"],
  },
  Automation: {
    stems: ["Flow", "Trigger", "Agent", "Ops", "Sync", "Automate"],
    audiences: ["operators", "ops teams", "founders", "internal tools teams"],
    benefits: ["remove repetitive work", "connect workflows cleanly", "automate handoffs", "run operations with less manual effort"],
  },
  "Business / CRM": {
    stems: ["CRM", "Pipeline", "Client", "Deal", "Ops", "Account"],
    audiences: ["sales teams", "ops teams", "business teams", "service firms"],
    benefits: ["manage pipelines better", "organize customer work", "streamline internal operations", "turn business data into action"],
  },
  Analytics: {
    stems: ["Metric", "Insight", "Signal", "Trend", "Pulse", "Intel"],
    audiences: ["growth teams", "analysts", "brands", "ops teams"],
    benefits: ["spot trends early", "measure performance cleanly", "understand audience signals", "turn data into decisions faster"],
  },
  "Avatar / Video Avatar": {
    stems: ["Avatar", "Presenter", "Persona", "Studio", "Speaker", "Face"],
    audiences: ["training teams", "creators", "brands", "marketing teams"],
    benefits: ["create avatar videos quickly", "localize presenter content", "scale spokesperson workflows", "publish synthetic video content faster"],
  },
  Advertising: {
    stems: ["Ad", "Creative", "Media", "Bid", "Campaign", "Audience"],
    audiences: ["paid media teams", "agencies", "growth teams", "brands"],
    benefits: ["produce ad creatives faster", "test campaigns quicker", "improve media performance", "scale paid acquisition workflows"],
  },
};

const generatedNamePrefixes = [
  "Nova",
  "Atlas",
  "Signal",
  "Orbit",
  "Prism",
  "Lumen",
  "Shift",
  "Pulse",
  "Vector",
  "Spark",
  "Forge",
  "Clarity",
  "Boost",
  "Layer",
  "Pilot",
  "Vertex",
  "Echo",
  "Nimbus",
  "Apex",
  "Cobalt",
];

const generatedNameSuffixes = [
  "AI",
  "Flow",
  "Labs",
  "Studio",
  "Core",
  "Cloud",
  "Works",
  "Desk",
  "Grid",
  "Stack",
  "Pilot",
  "Kit",
  "Base",
  "Scout",
  "Engine",
  "Sync",
];

const pricingRotation = ["Free", "Free Trial", "Paid", "Free Trial", "Paid", "Free Trial"];
const targetToolCount = 500;

export const categories = broadCategories;

const curatedTools = toolEntries.map(([name, category, pricing, description], index) =>
  buildToolDocument({
    name,
    category,
    pricing,
    description,
    websiteUrl: websiteUrlMap[name],
    index,
  })
);

const generatedTools = [];
const usedNames = new Set(curatedTools.map((tool) => tool.name.toLowerCase()));
const usedSlugs = new Set(curatedTools.map((tool) => tool.slug));

for (const [categoryIndex, category] of broadCategories.entries()) {
  const config = generatedCategoryConfig[category.name];

  if (!config) {
    continue;
  }

  for (let itemIndex = 0; itemIndex < 40 && curatedTools.length + generatedTools.length < targetToolCount; itemIndex += 1) {
    const prefix = generatedNamePrefixes[(categoryIndex + itemIndex) % generatedNamePrefixes.length];
    const stem = config.stems[itemIndex % config.stems.length];
    const suffix = generatedNameSuffixes[(categoryIndex * 3 + itemIndex) % generatedNameSuffixes.length];
    const name = `${prefix} ${stem} ${suffix}`;
    const slug = createSlug(name);

    if (usedNames.has(name.toLowerCase()) || usedSlugs.has(slug)) {
      continue;
    }

    const audience = config.audiences[itemIndex % config.audiences.length];
    const benefit = config.benefits[itemIndex % config.benefits.length];
    const pricing = pricingRotation[(categoryIndex + itemIndex) % pricingRotation.length];
    const description = `${category.name} workspace for ${audience} to ${benefit}.`;
    const websiteUrl = `https://${slug}.ai`;
    const tool = buildToolDocument({
      name,
      category: category.name,
      pricing,
      description,
      websiteUrl,
      index: curatedTools.length + generatedTools.length,
      extraTags: ["Seeded", "Directory"],
    });

    tool.image.url = getAvatarLogoUrl(name);

    generatedTools.push(tool);
    usedNames.add(name.toLowerCase());
    usedSlugs.add(slug);
  }
}

export const tools = [...curatedTools, ...generatedTools].slice(0, targetToolCount);
